### ISSUE TITLE
Suggestions and Comments in Conole Project

### ISSUE THREAD

**Issue by ramina1964** [ramina1964/NQueenCore#13]
- I can't understand the function of "Display Mode" property as a console app hasn't the ability to show the solution build up anyway. 
 - Furthermore, I can't see this property when I run the application.
 - The "Board Size" should be validated (in addition to format check already in place) as follows (square braces means both 
   ends included):
    - For A "Single Solution" in the range [1, 37].
    - For A "Unique Solutions" and "All Solutions" in the range [1,17].
 - Under execution, it would be easier and less error prone to make the user choose from a numerical menu, e.g. 1, 2, 3. 
 
If you agree with these suggestions; I could do it myself.

**Comment by lepned** [comment]
Have you pulled the last version from github. I thought I removed displaymode from console app.

**Comment by ramina1964** [comment]
No, I do it now. What about the other suggestions?

**Comment by lepned** [comment]
Yes, I agree with your suggestions. Please implement :)

**Comment by ramina1964** [comment]
Dette sa masteren selv 🙂

________________________________

**Comment by ramina1964** [comment]
Implemented all suggestions and code refactoring in form of extracting new methods and adding several properties.
