### ISSUE TITLE
Add console app to application to enable NQueen from command line

### ISSUE THREAD

**Issue by lepned** [ramina1964/NQueenCore#2]
To increase functionality and demonstrate free coupling from GUI-frameworks enable a command line tool to run NQueen without GUI. 

Should probably add some arguments to the command line for testing different board sizes and enable logging and debugging to console when you run the application.

**Comment by ramina1964** [comment]
The command line arguments of this app should be the boardSize, and SolutionMode and should return a List<Solution>

**Comment by ramina1964** [comment]
Validity of input parameters follows the same rules as the application with GUI, but due to lack of GUI considerable lower memory and CPU footage,

**Comment by lepned** [comment]
Did add console app to solution with limited functionality

**Comment by ramina1964** [comment]
Added
